### ISSUE TITLE
Falar com fabricante do motor sobre tensão de alimentação ser 24 volts

### ISSUE THREAD

**Issue by hemanuela-fernandes** [Ararabots-UFMS/vsss24-ws#117]
# **Objetivos:**
*Verificar se o motor roda com 24 volts*
- **Contexto:** O solenoide é alimentado com 24 V e a bateria fornece uma tensão menor que a tensão de alimentação do solenoide e dos motores. E desta forma, se conseguirmos alimentar os motores com 24V será necessário apenas um circuito de step up.
- **Resultado Esperado:** saber se é possível alimentar o motor com 24V.

# Critérios de Aceite:
- Ter a resposta do fabricante.

# Tarefas:
- [ ] entrar em contato com o fabricante.

**Comment by AmandaOp** [comment]
Mensagem do fabricante: We have not found your order information. We recommend that you use the voltage recommended in the specification to avoid unnecessary damage.

Dessa forma, teremos que usar uma tensão de alimentação de 20V
