### ISSUE TITLE
Selecionar Sensor infravermelho

### ISSUE THREAD

**Issue by hemanuela-fernandes** [Ararabots-UFMS/vsss24-ws#120]
# **Objetivos:**
*Selecionar um modelo de sensor infravermelho que atenda às necessidades de projeto.*
- **Contexto:** Precisamos prever quando a bola está na posição correta para o chute.
- **Resultado Esperado:** Ter um sensor infravermelho definido para o projeto.

# Critérios de Aceite:
- O sensor deve detectar objetos a uma distância que foi definida no projeto.

# Tarefas:
- [x] Pesquisar opções de sensores infravermelhos.
- [x] Ter as informações resultantes da pesquisa em fácil acesso.

**Comment by AmandaOp** [comment]
Ir Tcrt5000 - Faixa efetiva de medição entre 0,2 mm e 15 mm
Sensor de Obstáculos Reflexivo Infravermelho - 2 à 30cm
