### ISSUE TITLE
Definição de requisitos de um robô

### ISSUE THREAD

**Issue by viniciosfaustino** [Ararabots-UFMS/vsss24-ws#15]
# **Objetivos:**
*Definir tudo o que o robô deve fazer para ser funcional com o objetivo de competir na categoria SSL-EL*
- **Cenário:** "Como houve mudança de categoria as regras da extinta (e saudosa) VSSS não se aplicam ao novo robô. Com isso, é necessário que se tenha listado todos os comportamentos e ações esperadas para o novo robô"
- **Problema:** Não temos o conjunto de regras e comportamentos do robô da nova categoria.
- **Resultado Esperado:** "Uma listagem coesa de todos os comportamentos do robô, definições de tamanho, peso, qual a abordagem de controle e comunicação e limitações."

# Critérios de Aceite:
- Ter um documento onde conste quais são as regras vigentes 
- Ter a lista com os requisitos dos robôs
- Ter disponibilizado todos os documentos gerados em local de fácil acesso
- Ter todos os documentos validados pelos membros
- Ter os requisitos físicos(mecânica, hardware) validados com o Iaione
- "Critério 2" - o vice contra ataca e o inimigo agora é outro ~(é o 5)~ (agora é o 6)

# Tarefas:
- [x] ler as regras da SSL
- [x] consultar as regras que estão sendo discutidas no discord
- [x] criar o resumo de regras e disponibilizar
- [x] criar a lista de requisitos e disponibilizar
- [x] mandar os requisitos físicos do robô para o Iaione

**Comment by Menchik** [comment]
As três primeiras tarefas já haviam sido feitas, pelo menos parciamente, então só coloquei em um lugar onde todos possam acessar: [link do drive](https://drive.google.com/drive/folders/1yS6QY5tqdLsk0OZQvznH1G0exJXAvOaW?usp=sharing)
