### ISSUE TITLE
Realizar um levantamento dos requisitos do sistema (software)

### ISSUE THREAD

**Issue by viniciosfaustino** [Ararabots-UFMS/vsss24-ws#28]
# **Objetivos:**
*Possuir um levantamento de todos os requisitos do sistema*
- **Cenário:** Precisamos definir os requisitos que serão necessários no sistema SSL-EL.
- **Problema:** Não há entendimento completo do funcionamento do sistema bem como os requisitos para a SSL-EL.
- **Resultado Esperado:** Ter um levantamento dos requisitos funcionais do sistema organizados por módulo/contexto.

# Critérios de Aceite:
- Garantir que todos os requisitos do sistema estejam listados
- Garantir que os requisitos estejam divididos em categorias/contextos/módulos. Ex.: UI, controle, estratégia, etc...
- Garantir que todos os membros estejam de acordo com a listagem dos requisitos do sistema SSL-EL

# Tarefas:
- [x] Criar um documento compartilhado para agrupar todas as informações
- [x] Definir os requisitos do sistema
- [x] Definir módulos para agrupar esses requisitos
- [x] Desenhar um diagrama para facilitar leitura e entendimento

**Comment by FabioHuang** [comment]
https://drive.google.com/drive/u/2/folders/1GDJG77v35W4zra7cfXgJ4rxqkiOpgV1X

**Comment by FabioHuang** [comment]
[Requisitos-1.pdf](https://github.com/Ararabots-UFMS/vsss24-ws/files/14866271/Requisitos-1.pdf)
