### ISSUE TITLE
Listar arquiteturas de software que melhor se encaixam com os requisitos e suas características

### ISSUE THREAD

**Issue by Menchik** [Ararabots-UFMS/vsss24-ws#31]
# **Objetivos:**
*Construir uma base de conhecimento sobre diversas arquiteturas de software para ter como referência futura.*
- **Cenário:** Precisamos definir uma arquitetura para desenvolver o sistema.
- **Problema:** Não temos conhecimento suficiente para decidir de forma assertiva a arquitetura do software.
- **Resultado Esperado:** Uma listagem de características de arquiteturas encontradas.

# Critérios de Aceite:
- Ter os cenários ideias de aplicação das arquiteturas.
- Ter os prós e contras de cada arquitetura.
- Ter diagramas representativos de cada arquitetura.
- Ter uma descrição de como aplicar cada arquitetura.

# Tarefas:
- [x] Listar as arquiteturas estudadas.
- [x] Descrever cenários aplicáveis de cada arquitetura.
- [x] Consultar especialistas na área sobre recomendações de arquitetura.
- [x] Incluir diagramas informativos das arquiteturas.

**Comment by Marcelo-Filho112** [comment]
https://www.cs.cmu.edu/~reids/papers/Robot_Architectures.pdf
https://arxiv.org/pdf/1701.05453.pdf
