### ISSUE TITLE
Reestruturar template dos itens para ser mais aderente

### ISSUE THREAD

**Issue by viniciosfaustino** [Ararabots-UFMS/vsss24-ws#37]
O template para as issues proposto inicialmente contém campos que são redundantes e acabam dificultando e fazendo com que os refinamentos sejam mais longos que o necessário.

A ideia é utilizar da definição de preparado para formular perguntas que guiem a escrita de um card de maneira mais assertiva.

**Comment by FabioHuang** [comment]
# **Objetivos:**
%%% Objetivos da tarefa %%%
- **Contexto:** %%% Contexto em que a tarefa foi proposta e sua problemática %%%
- **Resultado Esperado:** %%% Qual de ve ser o resultado final %%%

# Critérios de Aceite:
-  %%%Critérios que devem ser cumpridos antes do item ser considerado pronto%%%

# Tarefas:
- [ ] %%%Passo a passo do que deve ser feito ("o que" e não "como")%%%
