### ISSUE TITLE
Criar um tutorial de como usar o simulador oficial da SSL

### ISSUE THREAD

**Issue by NatDuarte** [Ararabots-UFMS/vsss24-ws#39]
# **Objetivos:**
Estar habituado com a ferramenta de simulação da SSL (grSim).
- **Cenário:** Precisamos aprender a usar as ferramentas da SSL para facilitar no desenvolvimento.
- **Problema:** É necessário testar o VICE em ambiente simulado pois não teremos robô em boa parte do desenvolvimento.
- **Resultado Esperado:** Tutorial explicando como rodar e usar o grSim. 

# Critérios de Aceite:
- Ter um documento que explique como instalar grSim.
- Ter definido as funções basicas do software e como usá-las.

# Tarefas:
- [x] Instalar grSim.
- [x] Explorar suas principais funcionalidades.
- [x] Listar passo a passo das tarefas acima.

**Comment by Menchik** [comment]
https://docs.google.com/document/d/1A_02Tt_JWGRYRZ5XffDYGp0fcNXXA9pO3hKXNByXR44/edit?usp=drive_link
