### ISSUE TITLE
Definir requisitos da interface gráfica

### ISSUE THREAD

**Issue by Menchik** [Ararabots-UFMS/vsss24-ws#43]
# **Objetivos:**
*Ter os requisitos da interface gráfica documentados*
- **Contexto:** Para decidirmos qual vai ser o MVP da interface gráfica, precisamos ter os requisitos estabelecidos.
- **Resultado Esperado:** Documento com os requisitos fucionais, não funcionais e adicionais da interface gráfica

# Critérios de Aceite:
- Ter um documento de requisitos fucionais, não funcionais e adicionais da interface gráfica.
- Validar com os outros membros.

# Tarefas:
- [x] Criar o documento em local de fácil acesso
- [x] Definir usuários da interface
- [x] Definir os requisitos funcionais
- [x] Definir os requisitos não funcionais
- [x] Definir os requisitos adicionais

**Comment by Marcelo-Filho112** [comment]
https://drive.google.com/drive/u/1/folders/1FOqL96enDlGDrI-QKTSUDScfhtdI-WPH
