### ISSUE TITLE
Criar protótipo da interface gráfica

### ISSUE THREAD

**Issue by Menchik** [Ararabots-UFMS/vsss24-ws#44]
# **Objetivos:**
*Ter um protótipo para usar como base no desenvolvimento da interface gráfica.*
- **Contexto:** Para conseguirmos codar a interface gráfica no tempo determinado precisamos ter bem definido o que devemos fazer.
- **Resultado Esperado:** Protótipo no figma que atende os requisitos funcionais da interface gráfica. (#43)

# Critérios de Aceite:
- Precisa ser bonitinho.
- Validar com os outros membros.
- O protótipo precisa atender aos requisitos funcionais da interface gráfica.
- O protótipo precisa ser simples o bastante para ser codado posteriormente

# Tarefas:
- [x] Criar projeto no figma e colocar seu link nos comentários desse item.
- [x] Criar um protótipo incial que atende todos os requisitos.
- [x] Deixar bonitinho.

**Comment by Marcelo-Filho112** [comment]
https://www.figma.com/file/vjJ6u4YU6D0rK0EPzKX5i5/Ararabots-SSL---EL-%2F-Interface-Prototype?type=design&node-id=0-1&mode=design&t=fsFX54n7qnrKLt2L-0
