### ISSUE TITLE
Escrever um programa simples para usar o giroscópio com o STM32

### ISSUE THREAD

**Issue by AmandaOp** [Ararabots-UFMS/vsss24-ws#67]
# **Objetivos:**
*FamiLIArizar-se com o Giroscópio*
- **Contexto:** Temos pouca experiência com o STM32 e com o giroscópio e precisamos de uma aplicação simples para começar a desenvolver.
- **Resultado Esperado:** Ter um programa que leia os dados do giroscópio.

# Critérios de Aceite:
- Desenvolver o programa usando o ambiente de desenvolvimento da STM (Arduino);
- O programa deve mostrar os dados de leitura do giro;
- Usar o microcontrolador definido em #30 .

# Tarefas:
- [x] Aprender e conectar o giro no microcontrolador;
- [ ] Desenvolver um programa que faça leitura do giro pelo STM32.

**Comment by NatDuarte** [comment]
Encontramos uma  que tem tamanho menor que nossa memória flash [(link)](https://github.com/hideakitai/MPU9250) estamos com problemas para fazer funcionar, mesmo com confirmação de conexão com um firmware de teste ainda não conseguimos ler dados do giroscópio.

**Comment by NatDuarte** [comment]
No arquivo de teste de conexão [(link)](https://github.com/hideakitai/MPU9250/blob/master/examples/connection_check/connection_check.ino), temos na linha 37 onde o problema ocorre. O wire.available() retorna false mesmo o código anterior verificando a conexão I2C e o wire.read nunca é executado. Tirando a condição de execução do wire.read data recebe o valor de 0xFF, que não é um valor válido e o código seguinte fala que o módulo não é da série MPU.

**Comment by NatDuarte** [comment]
Acredito que compramos uma cópia não oficial do módulo e por isso não funciona, como ainda conseguimos pedir reembolso acredito que não vale a pena aprender a usá-lo.
