### ISSUE TITLE
Implementar o filtro de kalman para posição e velocidade 2D

### ISSUE THREAD

**Issue by Menchik** [Ararabots-UFMS/vsss24-ws#75]
# **Objetivos:**
Implementar o Filtro de Kalman 2D.
- **Contexto:** Os dados do reconhecimento feito pela ssl-vision são ruidosos, e existe a necessidade do cálculo de velocidade dos objetos para posteriormente ser usado nos algoritmos de movimentação. Tendo em vista esse problemas, o filtro de Kalman é a solução mais adequada, mais especificamente pela natureza não linear do movimento dos objetos, por isso o filtro de Kalman é o preferível.
- **Resultado Esperado:** Uma classe do filtro de Kalman 2D, implementado com Numpy, que calcule o passo de predição e o passo de update, com base no timestamp e posição(x,y) medida, e retorne o vetor de estado X [posição x; posição y; velocidade x; velocidade y].

# Critérios de Aceite:
- O filtro deve estimar o vetor de estado X de um objeto estacionário;
- O filtro deve estimar o vetor de estado X de um objeto movimento não acelerado;
- O filtro deve estimar o vetor de estado X de um objeto movimento com aceleração constante;

# Tarefas:
- [x] Definir as Matrizes necessárias.
- [x] Implementar o passo de predição.
- [x] Implementar o passo de update (baseado no timestamp e na posição x,y).

**Comment by FabioHuang** [comment]
Reference: 
    - "https://github.com/NickNair/Multiple-Object-Tracking-using-Kalman-Filter"
    - "https://github.com/LdDl/kalman-filter"

    Complementary documentation:

    - "https://machinelearningspace.com/2d-object-tracking-using-kalman-filter/"
    - "https://github.com/mabhisharma/Multi-Object-Tracking-with-Kalman-Filter/blob/master/kalmanFilter.py"
    - "https://cookierobotics.com/071/"
