### ISSUE TITLE
Decidir o algoritmo que vai ser usado para a movimentação

### ISSUE THREAD

**Issue by FabioHuang** [Ararabots-UFMS/vsss24-ws#80]
# **Objetivos:**
*Ter definido qual algoritmo será usado na movimentação*
- **Contexto:** Não sabemos qual algoritmo usar para a movimentação
- **Resultado Esperado:** Definir um algoritmo que atenda os requisitos de movimentação

# Critérios de Aceite:
- Ter definido os requisitos da movimentação
- Ter um documento de fácil acesso que justifique de forma clara a escolha

# Tarefas:
- [x] Definir os requisitos da movimentação
- [x] Pesquisar TDPs nesse contexto
- [x] Definir o algoritmo
- [x] Documentar as justificativas da escolha
- [x] Apresentar para a equipe para valiçãp

**Comment by AmandaOp** [comment]
Rapha - definir entre dois algoritmos

**Comment by Menchik** [comment]
Equipe: Vamos usar RRT pois é o que todo mundo usa.
