### ISSUE TITLE
Selecionar ESC's de motor compatível com motor de gimbal

### ISSUE THREAD

**Issue by AmandaOp** [Ararabots-UFMS/vsss24-ws#82]
# **Objetivos:**
Tornar possível o controle do motor de gimbal escolhido. (#30 )
- **Contexto:** Temos alguns ESC's mas precisamos obter mais.
- **Resultado Esperado:** Selecionar ESC compatível com o motor de gimbal.

# Critérios de Aceite:
- Selecionar ESC compatível.
- Validar com o Iaione.

# Tarefas:
- [x] Pesquisar sobre ESC que atendam as especificações do motor.
- [x] Apresentar para a equipe as opções disponíveis.
- [x] Selecionar o ESC.

**Comment by hemanuela-fernandes** [comment]
ESC 2-6s, Promoção $3,33 dol + frete saspy , aprox 15 dias pra chegar(pra mais)
https://pt.aliexpress.com/item/1005005657706475.html?src=google

**Comment by hemanuela-fernandes** [comment]
Esc 2-6s, R$214,95 (imposto + 95), frete grátis na primeira compra
https://produto.mercadolivre.com.br/MLB-4886302976-blheli-mini-30a-esc-opto-2-6s-para-multicits-oneshot42-_JM#position%3D4%26search_layout%3Dgrid%26type%3Ditem%26tracking_id%3D62d4114f-266a-4dcd-b2d1-6739d28a594d

**Comment by hemanuela-fernandes** [comment]
Esc 2-6s $4,4 dol, frete - $3,82 + frete aviao, +- 15 dias (pra mais)
https://www.aliexpress.us/item/3256807209170902.html?spm=a2g0o.productlist.main.9.63f137fdJ6Y0JO&algo_pvid=8bd8f63e-bd4f-4f32-9e4d-fc08fd2d13bb&algo_exp_id=8bd8f63e-bd4f-4f32-9e4d-fc08fd2d13bb-4&pdp_npi=4%40dis%21USD%216.48%214.41%21%21%2145.84%2131.17%21%402103010f17263475953255207e919c%2112000040571941843%21sea%21US%210%21ABX&curPageLogUid=ZvW5ApAxzk1O&utparam-url=scene%3Asearch%7Cquery_from%3A

**Comment by hemanuela-fernandes** [comment]
30A brushless ESC 2-6S (30g) - 
https://www.aliexpress.us/item/32997575055.html?spm=a2g0o.detail.pcDetailTopMoreOtherSeller.2.4140YFn5YFn5m6&gps-id=pcDetailTopMoreOtherSeller&scm=1007.40050.354490.0&scm_id=1007.40050.354490.0&scm-url=1007.40050.354490.0&pvid=35228109-fd04-4aa4-9c4a-1672373ac523&_t=gps-id%3ApcDetailTopMoreOtherSeller%2Cscm-url%3A1007.40050.354490.0%2Cpvid%3A35228109-fd04-4aa4-9c4a-1672373ac523%2Ctpp_buckets%3A668%232846%238112%231997&pdp_npi=4%40dis%21USD%215.33%210.99%21%21%215.33%210.99%21%402103246617266128927858763ead66%2166869719694%21rec%21US%21%21ABX&utparam-url=scene%3ApcDetailTopMoreOtherSeller%7Cquery_from%3A&gatewayAdapt=4itemAdapt


Como fica a entrega (saspy), frete, tempo de entrega: 
de Miami para Pedro juan: tempo de entrega até Miami (mais ou menos 8 dias úteis), e tempo de entrega da saspy (mais ou menos 7 dias, seg - sáb), tempo de eu ir buscar a compra (fim de semanas, ir na sexta/sábado e voltar no domingo/segunda).

preço do frete: aliexpress(acima de 10 dol, frete gratis) + saspy (Kg*$23,50) ou taxa minima de 100g ($2,35)

preço total: 
unidade - $5,72 + $4,12 (imposto) + $3,5 (frete aliexpress) + $2,35 (frete saspy)= $15,69 --> ± R$85,71

4 unidades - $22,88 + $10,21 (imposto) + $2,82 (frete saspy) = 	$35,91  ± R$196,16

Para entregar no Brasil direto:
± 11 - 22 dias úteis para chegar
unidade  R$ 33,70 + R$24,00 (frete) + R$25,81(taxa) = 85,72
4 unidades R$134,80 + R$60,14 (Taxa) = R$194,94

**Comment by AmandaOp** [comment]
ESC escolhido
https://www.aliexpress.us/item/32997575055.html?spm=a2g0o.detail.pcDetailTopMoreOtherSeller.2.4140YFn5YFn5m6&gps-id=pcDetailTopMoreOtherSeller&scm=1007.40050.354490.0&scm_id=1007.40050.354490.0&scm-url=1007.40050.354490.0&pvid=35228109-fd04-4aa4-9c4a-1672373ac523&_t=gps-id%3ApcDetailTopMoreOtherSeller%2Cscm-url%3A1007.40050.354490.0%2Cpvid%3A35228109-fd04-4aa4-9c4a-1672373ac523%2Ctpp_buckets%3A668%232846%238112%231997&pdp_npi=4%40dis%21USD%215.33%210.99%21%21%215.33%210.99%21%402103246617266128927858763ead66%2166869719694%21rec%21US%21%21ABX&utparam-url=scene%3ApcDetailTopMoreOtherSeller%7Cquery_from%3A&gatewayAdapt=4itemAdapt
